name: CI/CD Pipeline Maxwell

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout del codigo
        uses: actions/checkout@v4

      - name: 2. Configurar entorno Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 3. Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Ejecutar pruebas con Pytest
        run: |
          pytest -v

      - name: 5. Autenticar en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 6. Construir y subir imagen a Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mi-app-devops:latest

      - name: 7. Desplegar en Render
        env:
          RENDER_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -n "$RENDER_HOOK" ]; then
            curl -X POST "$RENDER_HOOK"
          else
            echo "RENDER_DEPLOY_HOOK no está configurado aún. Saltando despliegue."
          fi
